### ISSUE TITLE
Expanded Application Flexibility

### ISSUE THREAD

**Issue by Nirmit73** [SE-H-W/WolfJobs-Project3#7]
Allow multiple students or users to apply for the same job, ensuring efficient handling of simultaneous applications.

**Comment by AshwiniR1802** [comment]
ok i will implement that functionality

**Comment by AshwiniR1802** [comment]
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/699d2758-93f8-4eac-81d4-7ba17879f4a2">
Added now multiple users can apply for the same job.
